[package]
name = "overlay"
version = "0.1.0"
authors = ["Markus Røyset <maroider@protonmail.com>"]
edition = "2018"

[dependencies]
env_logger = "0.7.1"
imgui = "0.2.1"
imgui-wgpu = "0.4.1"
imgui-winit-support = { version = "0.2.1", default-features = false, features = ["winit-20"] }
wgpu = "0.4.0"
winit = "0.20.0-alpha4"
