[package]
name = "overlay"
version = "0.1.0"
authors = ["Markus Røyset <maroider@protonmail.com>"]
edition = "2018"

[dependencies]
winit = "0.20.0-alpha5"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3.8", features = ["windef", "winuser"] }
